import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { AnchorProvider, Program, Wallet, BN } from "@coral-xyz/anchor";
import type { EscrowClient, MatchState } from "./index";
import { matchPda, vaultPda } from "./index";

// Fill in after `anchor build && anchor deploy`:
const PROGRAM_ID_STR = process.env.PROGRAM_ID ?? "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS";
const RPC_URL = process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";

export class DevnetEscrowClient implements EscrowClient {
  private connection: Connection;
  private programId: PublicKey;

  // IDL is generated by `anchor build` — import lazily to avoid errors before build
  private program: any;

  constructor() {
    this.connection = new Connection(RPC_URL, "confirmed");
    this.programId = new PublicKey(PROGRAM_ID_STR);
  }

  private async getProgram(signerKeypair: Keypair) {
    if (!this.program) {
      // Import IDL after anchor build — will throw if build hasn't run
      let IDL: any;
      try {
        IDL = require("../../program/target/idl/pitch_battle.json");
      } catch {
        throw new Error(
          "IDL not found. Run `anchor build` inside /program first."
        );
      }
      const wallet = new Wallet(signerKeypair);
      const provider = new AnchorProvider(this.connection, wallet, {
        commitment: "confirmed",
      });
      this.program = new Program(IDL, this.programId, provider);
    }
    return this.program;
  }

  async createMatch(
    matchId: string,
    stakeLamports: number,
    p2: PublicKey,
    oracle: PublicKey,
    p1Keypair: Keypair
  ): Promise<{ matchId: string }> {
    const program = await this.getProgram(p1Keypair);
    const mPda = matchPda(matchId, this.programId);
    const vPda = vaultPda(matchId, this.programId);

    await program.methods
      .createMatch(matchId, new BN(stakeLamports), p2, oracle)
      .accounts({
        playerOne: p1Keypair.publicKey,
        matchAccount: mPda,
        vault: vPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([p1Keypair])
      .rpc();

    return { matchId };
  }

  async stake(matchId: string, player: Keypair): Promise<string> {
    const program = await this.getProgram(player);
    const mPda = matchPda(matchId, this.programId);
    const vPda = vaultPda(matchId, this.programId);

    const tx = await program.methods
      .stake(matchId)
      .accounts({
        signer: player.publicKey,
        matchAccount: mPda,
        vault: vPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([player])
      .rpc();

    return tx;
  }

  async settle(
    matchId: string,
    winner: PublicKey,
    oracleKeypair: Keypair
  ): Promise<string> {
    const program = await this.getProgram(oracleKeypair);
    const mPda = matchPda(matchId, this.programId);
    const vPda = vaultPda(matchId, this.programId);

    const tx = await program.methods
      .settle(matchId, winner)
      .accounts({
        oracle: oracleKeypair.publicKey,
        matchAccount: mPda,
        vault: vPda,
        winnerAccount: winner,
        systemProgram: SystemProgram.programId,
      })
      .signers([oracleKeypair])
      .rpc();

    return tx;
  }

  async refund(
    matchId: string,
    p1: PublicKey,
    p2: PublicKey,
    oracleKeypair: Keypair
  ): Promise<string> {
    const program = await this.getProgram(oracleKeypair);
    const mPda = matchPda(matchId, this.programId);
    const vPda = vaultPda(matchId, this.programId);

    const tx = await program.methods
      .refund(matchId)
      .accounts({
        oracle: oracleKeypair.publicKey,
        matchAccount: mPda,
        vault: vPda,
        playerOneAccount: p1,
        playerTwoAccount: p2,
        systemProgram: SystemProgram.programId,
      })
      .signers([oracleKeypair])
      .rpc();

    return tx;
  }

  async getMatch(matchId: string): Promise<MatchState> {
    // Use a throwaway keypair just to construct the provider for reads
    const program = await this.getProgram(Keypair.generate());
    const mPda = matchPda(matchId, this.programId);
    const m = await program.account.match.fetch(mPda);

    const stateKey = Object.keys(m.state)[0] as "open" | "staked" | "settled";
    const stateMap = { open: "Open", staked: "Staked", settled: "Settled" } as const;

    return {
      matchId: m.matchId,
      stakeLamports: m.stakeLamports.toNumber(),
      p1Staked: m.p1Staked,
      p2Staked: m.p2Staked,
      state: stateMap[stateKey],
      winner: m.winner ? (m.winner as PublicKey).toBase58() : null,
    };
  }

  async airdrop(pubkey: PublicKey, sol = 1): Promise<void> {
    const sig = await this.connection.requestAirdrop(pubkey, sol * LAMPORTS_PER_SOL);
    await this.connection.confirmTransaction(sig, "confirmed");
  }

  async getBalance(pubkey: PublicKey): Promise<number> {
    return this.connection.getBalance(pubkey);
  }
}
