"""run.py — real-time webcam pose matching against a precomputed reference.

Usage:
    python run.py [--ref reference_poses.json] [--camera 0] [--loop]

Controls:
    Q / ESC  — quit

Prerequisites:
    - reference_poses.json generated by extract_poses.py
    - pose_landmarker_full.task in the same directory
    - mediapipe >= 0.10, opencv-python, numpy

Sync: wall-clock time (not frame counters) so webcam FPS drift doesn't matter.
3-second countdown before playback starts so the user can get into position.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np

from pose_utils import similarity, normalize_pose, KEY_JOINTS, MIN_VISIBILITY

MODEL_PATH = Path(__file__).parent / "pose_landmarker_full.task"

# MediaPipe Pose connections (pairs of landmark indices)
CONNECTIONS = [
    (0, 1), (1, 2), (2, 3), (3, 7),
    (0, 4), (4, 5), (5, 6), (6, 8),
    (9, 10),
    (11, 12), (11, 13), (13, 15), (12, 14), (14, 16),
    (11, 23), (12, 24), (23, 24),
    (23, 25), (25, 27), (27, 29), (27, 31),
    (24, 26), (26, 28), (28, 30), (28, 32),
]


def _draw_skeleton(
    canvas: np.ndarray,
    landmarks: list[dict],
    color: tuple[int, int, int],
    w: int,
    h: int,
    dot_r: int = 4,
    line_w: int = 2,
    alpha: float = 1.0,
) -> None:
    """Draw a skeleton onto canvas. If alpha < 1, blends onto a copy."""
    if alpha < 1.0:
        overlay = canvas.copy()
    else:
        overlay = canvas

    for a, b in CONNECTIONS:
        if a >= len(landmarks) or b >= len(landmarks):
            continue
        if landmarks[a] is None or landmarks[b] is None:
            continue
        x1, y1 = int(landmarks[a]["x"] * w), int(landmarks[a]["y"] * h)
        x2, y2 = int(landmarks[b]["x"] * w), int(landmarks[b]["y"] * h)
        cv2.line(overlay, (x1, y1), (x2, y2), color, line_w, cv2.LINE_AA)

    for lm in landmarks:
        if lm is None:
            continue
        if lm.get("visibility", 1.0) < MIN_VISIBILITY:
            continue
        cx, cy = int(lm["x"] * w), int(lm["y"] * h)
        cv2.circle(overlay, (cx, cy), dot_r, color, -1, cv2.LINE_AA)

    if alpha < 1.0:
        cv2.addWeighted(overlay, alpha, canvas, 1.0 - alpha, 0, canvas)


def _draw_lm_list(
    canvas: np.ndarray,
    landmarks: list,  # MediaPipe NormalizedLandmark objects
    color: tuple[int, int, int],
    w: int,
    h: int,
    dot_r: int = 4,
    line_w: int = 2,
    alpha: float = 1.0,
) -> None:
    """Same as _draw_skeleton but for live MediaPipe landmark objects."""
    dicts = [{"x": lm.x, "y": lm.y, "visibility": getattr(lm, "visibility", 1.0)} for lm in landmarks]
    _draw_skeleton(canvas, dicts, color, w, h, dot_r, line_w, alpha)


def _score_color(score: float) -> tuple[int, int, int]:
    """Green for high, yellow for mid, red for low (BGR)."""
    if score >= 0.75:
        return (50, 220, 50)
    if score >= 0.5:
        return (30, 200, 220)
    return (50, 50, 220)


def countdown(cap: cv2.VideoCapture, seconds: int = 3) -> None:
    """Show a live countdown so the user can get into position."""
    start = time.time()
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        remaining = seconds - int(time.time() - start)
        if remaining <= 0:
            break
        frame = cv2.flip(frame, 1)
        h, w = frame.shape[:2]
        text = str(remaining)
        font = cv2.FONT_HERSHEY_SIMPLEX
        scale = 6.0
        thickness = 12
        (tw, th), _ = cv2.getTextSize(text, font, scale, thickness)
        cv2.putText(frame, text, ((w - tw) // 2, (h + th) // 2), font, scale, (0, 200, 255), thickness, cv2.LINE_AA)
        cv2.putText(frame, "Get in position!", (20, 50), font, 1.0, (255, 255, 255), 2, cv2.LINE_AA)
        cv2.imshow("Pose Match", frame)
        if cv2.waitKey(1) in (ord("q"), 27):
            sys.exit(0)


def run(ref_path: Path, camera: int, loop: bool) -> None:
    if not ref_path.exists():
        print(f"ERROR: reference file not found: {ref_path}", file=sys.stderr)
        print("Run extract_poses.py first.", file=sys.stderr)
        sys.exit(1)
    if not MODEL_PATH.exists():
        print(f"ERROR: model not found: {MODEL_PATH}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading reference poses from {ref_path}…")
    data = json.loads(ref_path.read_text())
    ref_fps: float = data["fps"]
    ref_frame_count: int = data["frame_count"]
    ref_frames: list[list[dict] | None] = data["frames"]
    duration_s = ref_frame_count / ref_fps
    print(f"  {ref_frame_count} frames @ {ref_fps:.2f} fps ({duration_s:.1f}s)")

    cap = cv2.VideoCapture(camera)
    if not cap.isOpened():
        print(f"ERROR: cannot open webcam at index {camera}. Try --camera 1.", file=sys.stderr)
        sys.exit(1)

    cam_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    cam_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    import mediapipe as mp
    from mediapipe.tasks.python import vision as mp_vision
    from mediapipe.tasks.python.core import base_options as mp_base

    opts = mp_vision.PoseLandmarkerOptions(
        base_options=mp_base.BaseOptions(model_asset_path=str(MODEL_PATH)),
        running_mode=mp_vision.RunningMode.VIDEO,
        num_poses=1,
        min_pose_detection_confidence=0.5,
        min_pose_presence_confidence=0.5,
        min_tracking_confidence=0.5,
    )

    print("Starting 3-second countdown…")
    countdown(cap, seconds=3)

    scores_history: list[float] = []
    frame_ts_ms: int = 0  # monotonically increasing timestamp for MediaPipe

    with mp_vision.PoseLandmarker.create_from_options(opts) as landmarker:
        t0 = time.time()
        while True:
            ok, bgr = cap.read()
            if not ok:
                print("ERROR: webcam read failed.", file=sys.stderr)
                break

            elapsed = time.time() - t0
            ref_idx = int(elapsed * ref_fps)

            if ref_idx >= ref_frame_count:
                if loop:
                    t0 = time.time()
                    elapsed = 0.0
                    ref_idx = 0
                    scores_history.clear()
                    print("\nLooping reference…")
                else:
                    print("\nReference ended.")
                    break

            # Flip webcam horizontally (mirror view)
            bgr = cv2.flip(bgr, 1)
            rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
            mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)

            frame_ts_ms += 33  # advance by ~33 ms per frame
            live_result = landmarker.detect_for_video(mp_image, frame_ts_ms)

            live_lms = live_result.pose_landmarks[0] if live_result.pose_landmarks else None
            ref_lms = ref_frames[ref_idx]

            # Draw reference skeleton (blue, 40% opacity)
            if ref_lms is not None:
                _draw_skeleton(bgr, ref_lms, (220, 100, 30), cam_w, cam_h, dot_r=5, line_w=2, alpha=0.4)

            # Draw live skeleton (green, solid)
            if live_lms is not None:
                _draw_lm_list(bgr, live_lms, (50, 220, 80), cam_w, cam_h, dot_r=5, line_w=3)

            # Compute similarity score
            live_dicts = None
            if live_lms is not None:
                live_dicts = [
                    {"x": lm.x, "y": lm.y, "z": lm.z, "visibility": getattr(lm, "visibility", 1.0)}
                    for lm in live_lms
                ]

            score: float | None = None
            if ref_lms is not None and live_dicts is not None:
                score = similarity(ref_lms, live_dicts)

            if score is not None:
                scores_history.append(score)
                if len(scores_history) > 30:
                    scores_history.pop(0)

            # ── HUD ─────────────────────────────────────────────────────────
            font = cv2.FONT_HERSHEY_SIMPLEX

            if score is not None:
                label = f"Score: {score:.2f}"
                color = _score_color(score)
                cv2.putText(bgr, label, (20, 70), font, 2.2, (0, 0, 0), 8, cv2.LINE_AA)
                cv2.putText(bgr, label, (20, 70), font, 2.2, color, 4, cv2.LINE_AA)
            elif ref_lms is None:
                cv2.putText(bgr, "No reference frame", (20, 70), font, 1.2, (120, 120, 120), 2)
            else:
                cv2.putText(bgr, "Move into frame", (20, 70), font, 1.4, (50, 50, 220), 3, cv2.LINE_AA)

            # Rolling average
            if scores_history:
                avg = sum(scores_history) / len(scores_history)
                cv2.putText(bgr, f"Avg: {avg:.2f}", (20, 115), font, 1.0, (200, 200, 200), 2, cv2.LINE_AA)

            # Frame counter / time
            time_str = f"{elapsed:.1f}s / {duration_s:.0f}s  [frame {ref_idx}/{ref_frame_count}]"
            cv2.putText(bgr, time_str, (20, cam_h - 16), font, 0.55, (160, 160, 160), 1, cv2.LINE_AA)
            cv2.putText(bgr, "Q = quit", (cam_w - 100, cam_h - 16), font, 0.55, (160, 160, 160), 1, cv2.LINE_AA)

            cv2.imshow("Pose Match", bgr)
            key = cv2.waitKey(1) & 0xFF
            if key in (ord("q"), ord("Q"), 27):
                break

    cap.release()
    cv2.destroyAllWindows()

    if scores_history:
        final_avg = sum(scores_history) / len(scores_history)
        print(f"Session average score: {final_avg:.3f}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Real-time webcam pose matching.")
    parser.add_argument("--ref", type=Path, default=Path("reference_poses.json"), help="Path to reference_poses.json")
    parser.add_argument("--camera", type=int, default=0, help="Webcam index (default: 0)")
    parser.add_argument("--loop", action="store_true", help="Loop the reference video when it ends")
    args = parser.parse_args()
    run(args.ref, args.camera, args.loop)


if __name__ == "__main__":
    main()
