[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
pitch_battle = "2eMwChdNVoxeoWjdaiTuBGasDiHCKN3jbw7dL5eSyuZf"

[programs.devnet]
pitch_battle = "2eMwChdNVoxeoWjdaiTuBGasDiHCKN3jbw7dL5eSyuZf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
